//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShoppingOnline.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Provider
    {
        public Provider()
        {
            this.Inwards = new HashSet<Inward>();
            this.Products = new HashSet<Product>();
        }
    
        public long ID { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public string Metatitle { get; set; }
        public string Description { get; set; }
        public Nullable<bool> Status { get; set; }
    
        public virtual ICollection<Inward> Inwards { get; set; }
        public virtual ICollection<Product> Products { get; set; }
    }
}
