//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShoppingOnline.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Serial_Type
    {
        public Serial_Type()
        {
            this.Inward_Detail = new HashSet<Inward_Detail>();
            this.Order_Detail = new HashSet<Order_Detail>();
        }
    
        public long ID { get; set; }
        public Nullable<long> Product_ID { get; set; }
        public string Size { get; set; }
        public string Color { get; set; }
        public string Image { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<bool> Status { get; set; }
    
        public virtual ICollection<Inward_Detail> Inward_Detail { get; set; }
        public virtual ICollection<Order_Detail> Order_Detail { get; set; }
        public virtual Product Product { get; set; }
    }
}
